services:
  - type: web
    name: ppt-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: PAYSTACK_PLAN_PRO_MONTHLY
        sync: false
      - key: PAYSTACK_PLAN_BUSINESS_MONTHLY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: temp
      mountPath: /tmp
      sizeGB: 1
