services:
  - type: web
    name: ppt-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: OPENAI_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ppt-generator-db
          property: connectionString
      - key: PAYSTACK_PLAN_PRO_MONTHLY
        sync: false
      - key: PAYSTACK_PLAN_BUSINESS_MONTHLY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: temp
      mountPath: /tmp
      sizeGB: 1

  - type: postgres
    name: ppt-generator-db
    plan: free
    ipAllowList: []
