services:
  - type: web
    name: ppt-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    disk:
      name: temp
      mountPath: /tmp
      sizeGB: 1
