services:
  - type: web
    name: decklyst
    env: python
    plan: free
    buildCommand: chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PATH
        value: /opt/render/project/venv/bin:/usr/local/bin:/usr/bin:/bin:${PATH}
      - key: PYTHONPATH
        value: /opt/render/project
      - key: VIRTUAL_ENV
        value: /opt/render/project/venv
      - key: OPENAI_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: decklyst-db
          property: connectionString
      - key: PAYSTACK_PLAN_PRO_MONTHLY
        sync: false
      - key: PAYSTACK_PLAN_BUSINESS_MONTHLY
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true
    disk:
      name: temp
      mountPath: /tmp
      sizeGB: 1

  - type: postgres
    name: decklyst-db
    plan: free
    ipAllowList: []
